version: '3.8'
services:
  # adminer:
  #   image: adminer:4-standalone
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - pg
  pg:
    image: "postgres:13-alpine"
    ports:
      - ${DB_MAIN_PORT}:5432
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_MAIN_DATABASE}
      POSTGRES_USER: ${DB_MAIN_USER}
      POSTGRES_PASSWORD: ${DB_MAIN_PASSWORD}
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379